import { notFound,redirect } from "next/navigation";
import { createSupabaseServerClient,hasSupabase } from "@/lib/supabase/server";
import { acceptQuote,createQuote } from "../actions";
export const metadata={title:"Commission request",robots:{index:false,follow:false}}; export const dynamic="force-dynamic";
const money=(kobo:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN"}).format(kobo/100);
export default async function RequestPage({params}:{params:Promise<{id:string}>}){
  if(!hasSupabase) redirect("/dashboard"); const client=await createSupabaseServerClient(); const {data:{user}}=await client.auth.getUser(); if(!user) redirect("/auth/login");
  const id=(await params).id; const {data:request}=await client.from("commission_requests").select("*,artists!inner(id,business_name,owner_user_id,slug)").eq("id",id).maybeSingle(); if(!request) notFound();
  const isArtist=(request.artists as any).owner_user_id===user.id; const isCustomer=request.customer_id===user.id; if(!isArtist&&!isCustomer) notFound();
  const {data:quotes}=await client.from("quotes").select("*").eq("request_id",id).order("version",{ascending:false}); const latest=quotes?.[0];
  return <section className="admin-shell"><p className="eyebrow">Managed commission request</p><h1 className="profile-title">{request.title}</h1><p>Artist: <strong>{(request.artists as any).business_name}</strong> · {request.category}</p><div className="request-brief">{Object.entries(request.brief||{}).map(([key,value])=><div key={key}><small>{key.replaceAll("_"," ")}</small><p>{String(value)}</p></div>)}</div>
    {latest&&<article className="quote-card"><p className="eyebrow">Quote version {latest.version}</p><h2>{money(latest.customer_total_kobo)}</h2><p>{latest.deliverables}</p><dl><div><dt>Artwork/service</dt><dd>{money(latest.commissionable_kobo)}</dd></div><div><dt>Reimbursable costs</dt><dd>{money(latest.reimbursable_kobo)}</dd></div><div><dt>Platform commission</dt><dd>{money(latest.platform_fee_kobo)} deducted from artist earnings</dd></div><div><dt>Artist entitlement</dt><dd>{money(latest.artist_entitlement_kobo)}</dd></div></dl>{isCustomer&&!latest.accepted_at&&<form action={acceptQuote}><input type="hidden" name="quote_id" value={latest.id}/><button className="button">Accept written quote</button></form>}{latest.accepted_at&&<div className="status-message">Accepted</div>}</article>}
    {isArtist&&!latest?.accepted_at&&<form className="application-form quote-form" action={createQuote}><input type="hidden" name="request_id" value={id}/><h2>Send a written quote</h2><div className="field"><label>Deliverables</label><textarea name="deliverables" required/></div><div className="field-grid"><div className="field"><label>Commissionable amount (₦)</label><input name="commissionable_naira" type="number" min="1000" step="100" required/></div><div className="field"><label>Travel, shipping or other reimbursable costs (₦)</label><input name="reimbursable_naira" type="number" min="0" step="100" defaultValue="0"/></div></div><div className="field-grid"><div className="field"><label>Delivery date</label><input name="delivery_date" type="date" required/></div><div className="field"><label>Included revisions</label><input name="revisions" type="number" min="0" max="20" defaultValue="1" required/></div></div><div className="field"><label>Cancellation terms</label><textarea name="cancellation" required/></div><div className="field"><label>Usage and reproduction rights</label><textarea name="rights" required/></div><button className="button">Send quote</button></form>}
  </section>;
}
