import { NextResponse } from "next/server";
import { verifyPaystackWebhook } from "@/lib/paystack";
import { recordSuccessfulPaystackPayment } from "@/lib/payments";
import { createSupabaseAdminClient } from "@/lib/supabase/server";

export async function POST(request:Request){
  if(Number(request.headers.get("content-length")||0)>1_000_000)return NextResponse.json({error:"Payload too large"},{status:413});
  const raw=await request.text(); if(!verifyPaystackWebhook(raw,request.headers.get("x-paystack-signature"))) return NextResponse.json({error:"Invalid signature"},{status:401});
  let event:any;try{event=JSON.parse(raw);}catch{return NextResponse.json({error:"Invalid JSON"},{status:400});}if(!event?.event||!event?.data)return NextResponse.json({error:"Invalid event"},{status:400});const admin=createSupabaseAdminClient();
  if(event.event==="charge.success"){const key=`charge.success:${event.data.id||event.data.reference}`; await recordSuccessfulPaystackPayment(key,event.data);return NextResponse.json({received:true});}
  const eventKey=`${event.event}:${event.data.id||event.data.reference||event.data.transaction_reference}`;const {error:eventError}=await admin.from("paystack_events").insert({event_key:eventKey,event_type:event.event,payload:event});if(eventError?.code==="23505")return NextResponse.json({received:true,duplicate:true});if(eventError)throw eventError;
  if(["transfer.success","transfer.failed","transfer.reversed"].includes(event.event)){const status=event.event.split(".")[1];const {data:payout}=await admin.from("payouts").update({status,failure_reason:event.data.reason||null,updated_at:new Date().toISOString()}).eq("reference",event.data.reference).select("booking_id,amount_kobo,reference").maybeSingle();if(payout&&status==="success")await admin.from("ledger_entries").upsert({booking_id:payout.booking_id,account:"artist_payable",direction:"debit",amount_kobo:payout.amount_kobo,currency:"NGN",reference:`${payout.reference}:paid`},{onConflict:"account,direction,reference",ignoreDuplicates:true});if(payout&&status==="reversed"){const {data:paid}=await admin.from("ledger_entries").select("id").eq("reference",`${payout.reference}:paid`).maybeSingle();if(paid)await admin.from("ledger_entries").upsert({booking_id:payout.booking_id,account:"artist_payable",direction:"credit",amount_kobo:payout.amount_kobo,currency:"NGN",reference:`${payout.reference}:reversed`},{onConflict:"account,direction,reference",ignoreDuplicates:true});}}
  if(event.event==="refund.processed"){const reference=event.data.transaction_reference||event.data.transaction?.reference;const {data:attempt}=await admin.from("payment_attempts").select("booking_id").eq("reference",reference).eq("status","success").maybeSingle();if(attempt){const {data:booking}=await admin.from("bookings").update({status:"refunded",updated_at:new Date().toISOString()}).eq("id",attempt.booking_id).eq("status","refund_pending").select("id,customer_total_kobo,artist_entitlement_kobo,platform_fee_kobo,currency").maybeSingle();if(booking){await Promise.all([admin.from("booking_status_history").insert({booking_id:booking.id,from_status:"refund_pending",to_status:"refunded",reason:"Paystack confirmed refund"}),admin.from("reviews").update({moderation_status:"hidden",updated_at:new Date().toISOString()}).eq("booking_id",booking.id)]);await admin.from("ledger_entries").insert([{booking_id:booking.id,account:"customer_funds",direction:"credit",amount_kobo:booking.customer_total_kobo,currency:booking.currency,reference:`${reference}:refund-customer`},{booking_id:booking.id,account:"artist_payable",direction:"debit",amount_kobo:booking.artist_entitlement_kobo,currency:booking.currency,reference:`${reference}:refund-artist`},{booking_id:booking.id,account:"platform_revenue",direction:"debit",amount_kobo:booking.platform_fee_kobo,currency:booking.currency,reference:`${reference}:refund-platform`}]);}}}
  if(event.event==="charge.dispute.create"){const reference=event.data.transaction?.reference||event.data.transaction_reference;const {data:attempt}=await admin.from("payment_attempts").select("booking_id").eq("reference",reference).maybeSingle();if(attempt){const {data:booking}=await admin.from("bookings").select("status").eq("id",attempt.booking_id).maybeSingle();if(booking&&!["refunded","refund_pending","cancelled","disputed"].includes(booking.status)){const {data:changed}=await admin.from("bookings").update({status:"disputed",updated_at:new Date().toISOString()}).eq("id",attempt.booking_id).eq("status",booking.status).select("id").maybeSingle();if(changed)await admin.from("booking_status_history").insert({booking_id:attempt.booking_id,from_status:booking.status,to_status:"disputed",reason:"Paystack charge dispute opened"});}}}
  return NextResponse.json({received:true});
}
