"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createSupabaseAdminClient, createSupabaseServerClient, hasSupabase } from "@/lib/supabase/server";
import { finalizePaystackTransfer, initiatePaystackRefund, initiatePaystackTransfer, verifyPaystackTransfer } from "@/lib/paystack";

async function requireUser() {
  if (!hasSupabase) throw new Error("Supabase is not configured.");
  const client = await createSupabaseServerClient();
  const { data: { user } } = await client.auth.getUser();
  if (!user || String(user.app_metadata?.role || "") !== "admin") throw new Error("Not authorized.");
  return client;
}

export async function updateArtistVerification(formData:FormData){const client=await requireUser();if(!process.env.SUPABASE_SERVICE_ROLE_KEY)throw new Error("Service role key is missing.");const id=String(formData.get("id"));const verification=String(formData.get("verification_state"));const bookable=formData.get("bookable")==="on";const recipient=String(formData.get("paystack_recipient_code")||"").trim()||null;if(!["researched","contacted","claimed","identity_verified","portfolio_approved","payment_ready","suspended"].includes(verification))throw new Error("Invalid verification state.");const admin=createSupabaseAdminClient();const {data:artist}=await admin.from("artists").select("owner_user_id").eq("id",id).maybeSingle();if(!artist)throw new Error("Artist not found.");if(bookable&&(verification!=="payment_ready"||!artist.owner_user_id||!recipient))throw new Error("Booking requires an owner account, payment-ready verification and a Paystack recipient.");const {error}=await admin.from("artists").update({verification_state:verification,bookable,paystack_recipient_code:recipient,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;await admin.from("audit_logs").insert({actor_id:(await client.auth.getUser()).data.user!.id,action:"artist.verification.updated",entity_type:"artist",entity_id:id,metadata:{verification,bookable}});revalidateDirectory();}
export async function approveArtistClaim(formData:FormData){const client=await requireUser();const admin=createSupabaseAdminClient();const claimId=String(formData.get("claim_id"));const reviewer=(await client.auth.getUser()).data.user!;const {error}=await admin.rpc("approve_artist_claim",{p_claim_id:claimId,p_reviewer:reviewer.id});if(error)throw error;revalidateDirectory();}
export async function moderatePublicContent(formData:FormData){const client=await requireUser();const table=String(formData.get("table"));if(!["reviews","artist_updates"].includes(table))throw new Error("Invalid moderation target.");const status=String(formData.get("status"));if(!["published","rejected","hidden"].includes(status))throw new Error("Invalid moderation state.");const id=String(formData.get("id"));const admin=createSupabaseAdminClient();if(status==="published"&&table==="reviews"){const {data:review}=await admin.from("reviews").select("bookings!inner(status)").eq("id",id).maybeSingle();if((review?.bookings as any)?.status!=="completed")throw new Error("Only reviews for completed, non-refunded bookings can be published.");}if(status==="published"&&table==="artist_updates"){const {data:update}=await admin.from("artist_updates").select("visibility,client_consent,expires_at").eq("id",id).maybeSingle();if(!update||update.visibility!=="public"||!update.client_consent||new Date(update.expires_at)<=new Date())throw new Error("This public update is not eligible for publication.");}const {error}=await admin.from(table).update({moderation_status:status}).eq("id",id);if(error)throw error;const actor=(await client.auth.getUser()).data.user!;await admin.from("audit_logs").insert({actor_id:actor.id,action:`${table}.moderated`,entity_type:table,entity_id:id,metadata:{status}});revalidateDirectory();}
export async function releaseArtistPayout(formData:FormData){const client=await requireUser();if(process.env.PAYSTACK_PAYOUTS_ENABLED!=="true")throw new Error("Live payouts are disabled until Paystack approves delayed marketplace settlement.");const bookingId=String(formData.get("booking_id"));const admin=createSupabaseAdminClient();const {data:booking}=await admin.from("bookings").select("*,artists!inner(paystack_recipient_code,business_name)").eq("id",bookingId).maybeSingle();if(!booking||booking.status!=="completed"||!booking.payout_eligible_at||new Date(booking.payout_eligible_at)>new Date())throw new Error("Payout is not eligible.");const recipient=(booking.artists as any).paystack_recipient_code;if(!recipient)throw new Error("Artist payout recipient is missing.");const reference=`AIN-PAYOUT-${booking.id}`;const actor=(await client.auth.getUser()).data.user!;const {data:existing}=await admin.from("payouts").select("id,status").eq("booking_id",booking.id).maybeSingle();if(existing&&!["failed","reversed"].includes(existing.status))throw new Error("A payout is already active for this booking.");if(existing){const {error}=await admin.from("payouts").update({status:"initializing",failure_reason:null,updated_at:new Date().toISOString(),initiated_by:actor.id}).eq("id",existing.id);if(error)throw error;}else{const {error}=await admin.from("payouts").insert({booking_id:booking.id,artist_id:booking.artist_id,amount_kobo:booking.artist_entitlement_kobo,recipient_code:recipient,reference,status:"initializing",initiated_by:actor.id});if(error)throw error;}try{const result=await initiatePaystackTransfer({amountKobo:booking.artist_entitlement_kobo,recipientCode:recipient,reference,reason:`Artist in Nigeria commission ${booking.id}`});const {error}=await admin.from("payouts").update({transfer_code:result.transfer_code,status:result.status,updated_at:new Date().toISOString()}).eq("booking_id",booking.id);if(error)throw error;}catch(error){await admin.from("payouts").update({status:"failed",failure_reason:error instanceof Error?error.message:"Transfer request failed",updated_at:new Date().toISOString()}).eq("booking_id",booking.id);throw error;}await admin.from("audit_logs").insert({actor_id:actor.id,action:"payout.requested",entity_type:"booking",entity_id:booking.id,metadata:{reference,amount_kobo:booking.artist_entitlement_kobo}});revalidatePath("/admin");}
export async function finalizeArtistPayout(formData:FormData){const client=await requireUser();if(process.env.PAYSTACK_PAYOUTS_ENABLED!=="true")throw new Error("Live payouts are disabled.");const bookingId=String(formData.get("booking_id")),otp=String(formData.get("otp")||"").trim();if(!/^\d{6}$/.test(otp))throw new Error("Enter the six-digit Paystack transfer OTP.");const admin=createSupabaseAdminClient();const {data:payout}=await admin.from("payouts").select("id,transfer_code,status").eq("booking_id",bookingId).maybeSingle();if(!payout||payout.status!=="otp"||!payout.transfer_code)throw new Error("This payout is not awaiting OTP approval.");const result=await finalizePaystackTransfer(payout.transfer_code,otp);const {error}=await admin.from("payouts").update({status:result.status,updated_at:new Date().toISOString()}).eq("id",payout.id).eq("status","otp");if(error)throw error;const actor=(await client.auth.getUser()).data.user!;await admin.from("audit_logs").insert({actor_id:actor.id,action:"payout.otp_finalized",entity_type:"booking",entity_id:bookingId,metadata:{transfer_code:payout.transfer_code,status:result.status}});revalidatePath("/admin");}
export async function reconcileArtistPayout(formData:FormData){const client=await requireUser();const bookingId=String(formData.get("booking_id"));const admin=createSupabaseAdminClient();const {data:payout}=await admin.from("payouts").select("id,booking_id,reference,amount_kobo,status").eq("booking_id",bookingId).maybeSingle();if(!payout)throw new Error("Payout not found.");const result=await verifyPaystackTransfer(payout.reference);if(result.amount!==payout.amount_kobo||String(result.currency).toUpperCase()!=="NGN")throw new Error("Paystack payout amount or currency does not match the booking.");await admin.from("payouts").update({status:result.status,updated_at:new Date().toISOString()}).eq("id",payout.id);if(result.status==="success")await admin.from("ledger_entries").upsert({booking_id:payout.booking_id,account:"artist_payable",direction:"debit",amount_kobo:payout.amount_kobo,currency:"NGN",reference:`${payout.reference}:paid`},{onConflict:"account,direction,reference",ignoreDuplicates:true});if(result.status==="reversed"){const {data:paid}=await admin.from("ledger_entries").select("id").eq("reference",`${payout.reference}:paid`).maybeSingle();if(paid)await admin.from("ledger_entries").upsert({booking_id:payout.booking_id,account:"artist_payable",direction:"credit",amount_kobo:payout.amount_kobo,currency:"NGN",reference:`${payout.reference}:reversed`},{onConflict:"account,direction,reference",ignoreDuplicates:true});}const actor=(await client.auth.getUser()).data.user!;await admin.from("audit_logs").insert({actor_id:actor.id,action:"payout.reconciled",entity_type:"booking",entity_id:bookingId,metadata:{previous_status:payout.status,status:result.status,reference:payout.reference}});revalidatePath("/admin");}

async function requestFullRefund(bookingId:string,actorId:string){const admin=createSupabaseAdminClient();const {data:booking}=await admin.from("bookings").select("id,status").eq("id",bookingId).maybeSingle();if(!booking||!["funded","in_progress","awaiting_client_approval","revision_requested","completed","disputed"].includes(booking.status))throw new Error("Booking is not eligible for a refund.");const [{data:payment},{data:payout}]=await Promise.all([admin.from("payment_attempts").select("reference").eq("booking_id",bookingId).eq("status","success").maybeSingle(),admin.from("payouts").select("status").eq("booking_id",bookingId).maybeSingle()]);if(!payment)throw new Error("Successful payment not found.");if(payout&&!["failed","reversed"].includes(payout.status))throw new Error("Refund cannot start while an artist payout is active or completed.");const {data:changed,error}=await admin.from("bookings").update({status:"refund_pending",updated_at:new Date().toISOString()}).eq("id",bookingId).eq("status",booking.status).select("id").maybeSingle();if(error)throw error;if(!changed)throw new Error("Booking changed in another session. Refresh and try again.");try{const result=await initiatePaystackRefund(payment.reference);await Promise.all([admin.from("booking_status_history").insert({booking_id:bookingId,from_status:booking.status,to_status:"refund_pending",changed_by:actorId,reason:"Full refund requested through Paystack"}),admin.from("audit_logs").insert({actor_id:actorId,action:"refund.requested",entity_type:"booking",entity_id:bookingId,metadata:{payment_reference:payment.reference,provider_refund_id:result.id,status:result.status}})]);}catch(error){await admin.from("bookings").update({status:booking.status,updated_at:new Date().toISOString()}).eq("id",bookingId).eq("status","refund_pending");throw error;}}
export async function refundBooking(formData:FormData){const client=await requireUser();const actor=(await client.auth.getUser()).data.user!;await requestFullRefund(String(formData.get("booking_id")),actor.id);revalidatePath("/admin");}
export async function resolveDispute(formData:FormData){const client=await requireUser();const disputeId=String(formData.get("dispute_id"));const outcome=String(formData.get("outcome"));const resolution=String(formData.get("resolution")||"").trim();if(resolution.length<20)throw new Error("Record a complete dispute decision.");const admin=createSupabaseAdminClient();const {data:dispute}=await admin.from("disputes").select("*").eq("id",disputeId).eq("status","open").maybeSingle();if(!dispute)throw new Error("Open dispute not found.");const actor=(await client.auth.getUser()).data.user!;if(outcome==="refund")await requestFullRefund(dispute.booking_id,actor.id);else if(outcome==="complete"){const now=new Date();const {data:changed}=await admin.from("bookings").update({status:"completed",completed_at:now.toISOString(),payout_eligible_at:new Date(now.getTime()+72*3600000).toISOString(),updated_at:now.toISOString()}).eq("id",dispute.booking_id).eq("status","disputed").select("id").maybeSingle();if(!changed)throw new Error("The disputed booking changed before resolution.");await admin.from("booking_status_history").insert({booking_id:dispute.booking_id,from_status:"disputed",to_status:"completed",changed_by:actor.id,reason:resolution});}else throw new Error("Invalid dispute outcome.");await admin.from("disputes").update({status:"resolved",resolution,resolved_by:actor.id,resolved_at:new Date().toISOString()}).eq("id",disputeId).eq("status","open");revalidatePath("/admin");}

function featuredFields(formData: FormData) {
  const featured = formData.get("featured") === "on";
  const untilValue = String(formData.get("featured_until") || "").trim();
  return {
    featured,
    featured_until: featured && untilValue ? new Date(`${untilValue}T23:59:59.999Z`).toISOString() : null,
    featured_tier: featured ? String(formData.get("featured_tier") || "manual") : null,
  };
}

function revalidateDirectory() {
  revalidatePath("/", "layout");
}

export async function moderateArtist(formData: FormData) {
  const client=await requireUser();
  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) throw new Error("Service role key is missing.");
  const id = String(formData.get("id"));
  const status = String(formData.get("status"));
  if (!["approved", "rejected"].includes(status)) throw new Error("Invalid moderation status.");
  const reason=String(formData.get("moderation_reason")||"").trim();if(status==="rejected"&&(reason.length<10||reason.length>1000))throw new Error("Record a rejection reason between 10 and 1,000 characters.");
  const update = status === "approved"
    ? { status, moderation_reason:null, updated_at: new Date().toISOString(), ...featuredFields(formData) }
    : { status, moderation_reason:reason, bookable:false, updated_at: new Date().toISOString() };
  const admin = createSupabaseAdminClient();
  const { error } = await admin.from("artists").update(update).eq("id", id);
  if (error) throw error;
  const actor=(await client.auth.getUser()).data.user!;await admin.from("audit_logs").insert({actor_id:actor.id,action:`artist.${status}`,entity_type:"artist",entity_id:id,metadata:{reason:reason||null}});
  revalidateDirectory();
}

export async function updateFeaturedPlacement(formData: FormData) {
  await requireUser();
  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) throw new Error("Service role key is missing.");
  const admin = createSupabaseAdminClient();
  const { error } = await admin.from("artists").update({ ...featuredFields(formData), updated_at: new Date().toISOString() }).eq("id", String(formData.get("id")));
  if (error) throw error;
  revalidateDirectory();
}

export async function signOut() {
  const client = await requireUser();
  await client.auth.signOut();
  redirect("/admin/login");
}
