/* eslint-disable @next/next/no-img-element -- Application media is served directly from artist-owned storage. */
import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createSupabaseAdminClient,createSupabaseServerClient,hasSupabase } from "@/lib/supabase/server";
import type { Artist } from "@/lib/types";
import { approveArtistClaim,finalizeArtistPayout,moderateArtist,moderatePublicContent,reconcileArtistPayout,refundBooking,releaseArtistPayout,resolveDispute,signOut,updateArtistVerification,updateFeaturedPlacement } from "./actions";
export const metadata:Metadata={title:"Commission house administration",robots:{index:false,follow:false}};export const dynamic="force-dynamic";
function FeaturedFields({artist}:{artist?:Artist}){return <div className="featured-controls"><label className="choice"><input type="checkbox" name="featured" defaultChecked={artist?.featured||false}/> Featured after service/location match</label><div className="field-grid"><div className="field"><label>Tier</label><select name="featured_tier" defaultValue={artist?.featured_tier||"monthly"}><option>weekly</option><option>monthly</option><option>manual</option><option>owner</option></select></div><div className="field"><label>Until</label><input type="date" name="featured_until" defaultValue={artist?.featured_until?.slice(0,10)||""}/></div></div></div>}
export default async function AdminPage(){if(!hasSupabase||!process.env.SUPABASE_SERVICE_ROLE_KEY)redirect("/admin/login");const session=await createSupabaseServerClient();const {data:{user}}=await session.auth.getUser();if(!user||String(user.app_metadata?.role||"")!=="admin")redirect("/admin/login");const admin=createSupabaseAdminClient();const [{data:allArtists},{data:claims},{data:updates},{data:reviews},{data:completed},{data:disputes}]=await Promise.all([admin.from("artists").select("*").in("status",["pending","approved"]).order("created_at"),admin.from("artist_claims").select("*,artists(business_name)").eq("status","pending"),admin.from("artist_updates").select("*,artists(business_name)").eq("moderation_status","pending"),admin.from("reviews").select("*,artists(business_name)").eq("moderation_status","pending"),admin.from("bookings").select("*,artists(business_name,paystack_recipient_code),payouts(id,status)").eq("status","completed"),admin.from("disputes").select("*,bookings(id,artists(business_name))").eq("status","open")]);const artists=(allArtists||[]) as Artist[];const pending=artists.filter(a=>a.status==="pending"),approved=artists.filter(a=>a.status==="approved");return <section className="admin-shell"><div className="admin-heading"><div><p className="eyebrow">Private commission-house administration</p><h1>Operations</h1><p>{pending.length} artist applications · {claims?.length||0} claims · {reviews?.length||0} reviews · {disputes?.length||0} disputes</p></div><form action={signOut}><button className="button reject">Sign out</button></form></div>
  <Queue title="Artist applications" empty="No applications waiting.">{pending.map(artist=><article className="admin-card" key={artist.id}><div><h2>{artist.business_name}</h2><p><strong>{artist.owner_name}</strong> · {artist.email} · {artist.whatsapp}</p><p>{artist.bio}</p><div className="chips">{[...artist.categories,...artist.states_served].map(item=><span key={item}>{item}</span>)}</div>{artist.portfolio_image_urls.length>0&&<div className="admin-portfolio" aria-label={`${artist.business_name} submitted portfolio`}>{artist.portfolio_image_urls.map((url,index)=><img src={url} alt={`${artist.business_name} application artwork ${index+1}`} key={url}/>)}</div>}</div><div><form action={moderateArtist}><input type="hidden" name="id" value={artist.id}/><input type="hidden" name="status" value="approved"/><button className="button">Approve listing</button></form><form action={moderateArtist} style={{marginTop:8}}><input type="hidden" name="id" value={artist.id}/><input type="hidden" name="status" value="rejected"/><div className="field"><label>Reason shown to applicant</label><textarea name="moderation_reason" minLength={10} maxLength={1000} required/></div><button className="button reject">Reject</button></form></div></article>)}</Queue>
  <Queue title="Approved artist verification" empty="No approved profiles.">{approved.map(artist=><article className="admin-card" key={artist.id}><div><h2>{artist.business_name}</h2><p>{artist.categories.join(" · ")}<br/>{artist.states_served.join(" · ")}</p><form action={updateArtistVerification} className="verification-form"><input type="hidden" name="id" value={artist.id}/><div className="field"><label>Verification</label><select name="verification_state" defaultValue={artist.verification_state||"researched"}>{["researched","contacted","claimed","identity_verified","portfolio_approved","payment_ready","suspended"].map(value=><option key={value}>{value}</option>)}</select></div><div className="field"><label>Paystack recipient code</label><input name="paystack_recipient_code" defaultValue={artist.paystack_recipient_code||""}/></div><label className="choice"><input type="checkbox" name="bookable" defaultChecked={artist.bookable}/> Bookable</label><button className="button button-small">Save verification</button></form></div><form action={updateFeaturedPlacement}><input type="hidden" name="id" value={artist.id}/><FeaturedFields artist={artist}/><button className="button">Save ranking</button></form></article>)}</Queue>
  <Queue title="Profile claims" empty="No profile claims waiting.">{claims?.map((claim:any)=><article className="admin-card" key={claim.id}><div><h2>{claim.artists?.business_name}</h2><p>{claim.evidence}</p></div><form action={approveArtistClaim}><input type="hidden" name="claim_id" value={claim.id}/><button className="button">Approve ownership</button></form></article>)}</Queue>
  <Queue title="Public progress moderation" empty="No public updates waiting.">{updates?.map((item:any)=><ModerationCard key={item.id} table="artist_updates" id={item.id} title={item.artists?.business_name} body={item.caption}/>)}</Queue>
  <Queue title="Verified review moderation" empty="No reviews waiting.">{reviews?.map((item:any)=><ModerationCard key={item.id} table="reviews" id={item.id} title={`${item.artists?.business_name} · ${item.overall}/5`} body={item.body}/>)}</Queue>
  <Queue title="Open disputes" empty="No disputes awaiting a decision.">{disputes?.map((dispute:any)=><article className="admin-card" key={dispute.id}><div><h2>{dispute.bookings?.artists?.business_name||"Commission dispute"}</h2><p>{dispute.reason}</p>{dispute.bookings?.id&&<Link className="text-link" href={`/bookings/${dispute.bookings.id}`}>Review agreement, messages and files</Link>}</div><form action={resolveDispute}><input type="hidden" name="dispute_id" value={dispute.id}/><div className="field"><label>Decision</label><select name="outcome"><option value="complete">Commission completed</option><option value="refund">Refund customer</option></select></div><div className="field"><label>Recorded resolution</label><textarea name="resolution" minLength={20} required/></div><button className="button">Resolve dispute</button></form></article>)}</Queue>
  <Queue title="Completed booking payouts" empty="No completed bookings waiting.">{completed?.map((booking:any)=>{const payout=booking.payouts?.[0],retryable=!payout||["failed","reversed"].includes(payout.status);return <article className="admin-card" key={booking.id}><div><h2>{booking.artists?.business_name}</h2><p>Artist entitlement: ₦{(booking.artist_entitlement_kobo/100).toLocaleString("en-NG")}<br/>Payout eligible: {booking.payout_eligible_at?new Date(booking.payout_eligible_at).toLocaleString("en-NG"):"not scheduled"}<br/>Current payout: {payout?.status||"not released"}</p></div><div>{payout?.status==="otp"?<form action={finalizeArtistPayout}><input type="hidden" name="booking_id" value={booking.id}/><div className="field"><label>Paystack transfer OTP</label><input name="otp" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required/></div><button className="button">Finalize payout</button></form>:retryable?<form action={releaseArtistPayout}><input type="hidden" name="booking_id" value={booking.id}/><button className="button">Release payout</button></form>:<form action={reconcileArtistPayout}><input type="hidden" name="booking_id" value={booking.id}/><button className="button button-dark">Reconcile with Paystack</button></form>}{retryable&&<form action={refundBooking} style={{marginTop:8}}><input type="hidden" name="booking_id" value={booking.id}/><button className="button reject">Full refund</button></form>}</div></article>})}</Queue>
  </section>}
function Queue({title,empty,children}:{title:string;empty:string;children:React.ReactNode}){const count=Array.isArray(children)?children.length:children?1:0;return <section><div className="section-heading" style={{marginTop:80}}><h2>{title}</h2></div><div className="admin-list">{count?children:<div className="empty-state">{empty}</div>}</div></section>}
function ModerationCard({table,id,title,body}:{table:string;id:string;title:string;body:string}){return <article className="admin-card"><div><h2>{title}</h2><p>{body}</p></div><div className="admin-actions"><form action={moderatePublicContent}><input type="hidden" name="table" value={table}/><input type="hidden" name="id" value={id}/><input type="hidden" name="status" value="published"/><button className="button">Publish</button></form><form action={moderatePublicContent}><input type="hidden" name="table" value={table}/><input type="hidden" name="id" value={id}/><input type="hidden" name="status" value="rejected"/><button className="button reject">Reject</button></form></div></article>}
