/* eslint-disable @next/next/no-img-element -- Private signed media URLs expire and must not be cached by the image optimizer. */
import { notFound,redirect } from "next/navigation";
import { createSupabaseAdminClient,createSupabaseServerClient,hasSupabase } from "@/lib/supabase/server";
import { respondToReview,sendBookingMessage,submitReview,transitionBooking } from "../actions";
export const metadata={title:"Commission workspace",robots:{index:false,follow:false}}; export const dynamic="force-dynamic";
const money=(amount:number,currency="NGN")=>new Intl.NumberFormat("en-NG",{style:"currency",currency}).format(amount/100);
export default async function BookingPage({params}:{params:Promise<{id:string}>}){
  if(!hasSupabase) redirect("/dashboard"); const client=await createSupabaseServerClient(); const {data:{user}}=await client.auth.getUser(); if(!user) redirect("/auth/login"); const id=(await params).id;
  const {data:booking}=await client.from("bookings").select("*,artists!inner(business_name,owner_user_id,slug),commission_requests(title,category)").eq("id",id).maybeSingle(); if(!booking) notFound();
  const isCustomer=booking.customer_id===user.id,isArtist=(booking.artists as any).owner_user_id===user.id,isAdmin=String(user.app_metadata?.role||"")==="admin"; if(!isCustomer&&!isArtist&&!isAdmin) notFound();
  const [{data:messages},{data:history},{data:payment},{data:review},{data:privateUpdates}]=await Promise.all([client.from("booking_messages").select("*").eq("booking_id",id).order("created_at"),client.from("booking_status_history").select("*").eq("booking_id",id).order("created_at"),client.from("payment_attempts").select("reference,status,paid_at").eq("booking_id",id).order("created_at",{ascending:false}).limit(1).maybeSingle(),client.from("reviews").select("id,moderation_status,artist_response").eq("booking_id",id).maybeSingle(),client.from("artist_updates").select("id,caption,media_url,expires_at").eq("booking_id",id).eq("visibility","booking_private").gt("expires_at",new Date().toISOString()).order("created_at",{ascending:false})]);
  const admin=createSupabaseAdminClient();const renderedMessages=await Promise.all((messages||[]).map(async(message:any)=>{const paths=(message.attachment_urls||[]).filter((path:string)=>path.startsWith(`${id}/`));const attachments=await Promise.all(paths.map(async(path:string)=>{const {data}=await admin.storage.from("booking-files").createSignedUrl(path,900);return data?.signedUrl||null;}));return {...message,attachments:attachments.filter(Boolean)};}));const renderedUpdates=await Promise.all((privateUpdates||[]).map(async(update:any)=>{const {data}=await admin.storage.from("artist-updates").createSignedUrl(update.media_url,900);return {...update,signedUrl:data?.signedUrl||"",isVideo:/\.(mp4|webm)$/i.test(update.media_url)};}));
  const status=booking.status as string;
  return <section className="admin-shell"><div className="admin-heading"><div><p className="eyebrow">Protected commission workspace</p><h1>{(booking.commission_requests as any)?.title}</h1><p>{(booking.artists as any).business_name} · {(booking.commission_requests as any)?.category}</p></div><span className="status-pill status-large">{status.replaceAll("_"," ")}</span></div>
    <div className="workspace-grid"><article className="quote-card"><h2>{money(booking.customer_total_kobo,booking.currency)}</h2><dl><div><dt>Artist entitlement</dt><dd>{money(booking.artist_entitlement_kobo,booking.currency)}</dd></div><div><dt>Platform commission</dt><dd>{money(booking.platform_fee_kobo,booking.currency)} (10%)</dd></div><div><dt>Paystack reference</dt><dd>{payment?.reference||"Not paid"}</dd></div></dl><h3>Accepted agreement</h3><p>{booking.agreement_snapshot?.deliverables}</p><pre className="agreement-json">{JSON.stringify(booking.agreement_snapshot?.terms||{},null,2)}</pre>
      {isCustomer&&["quote_accepted","payment_pending"].includes(status)&&<form method="post" action="/api/payments/initialize"><input type="hidden" name="booking_id" value={id}/><button className="button">Pay securely with Paystack</button></form>}
      {isCustomer&&status==="quote_accepted"&&<StateButton id={id} to="cancelled" label="Cancel before payment"/>}
      {isArtist&&status==="funded"&&<StateButton id={id} to="in_progress" label="Acknowledge and begin"/>}
      {isArtist&&["in_progress","revision_requested"].includes(status)&&<StateButton id={id} to="awaiting_client_approval" label="Submit work for approval"/>}
      {isCustomer&&status==="awaiting_client_approval"&&<div className="dashboard-actions"><StateButton id={id} to="completed" label="Approve completed work"/><ReasonButton id={id} to="revision_requested" label="Request revision"/><ReasonButton id={id} to="disputed" label="Open dispute"/></div>}
      {isCustomer&&["funded","in_progress"].includes(status)&&<ReasonButton id={id} to="disputed" label="Open dispute"/>}
      {(isCustomer||isArtist)&&status==="completed"&&booking.payout_eligible_at&&new Date(booking.payout_eligible_at)>new Date()&&<ReasonButton id={id} to="disputed" label="Open dispute before payout"/>}
      {isArtist&&["funded","in_progress","awaiting_client_approval","revision_requested"].includes(status)&&<ReasonButton id={id} to="disputed" label="Open artist dispute"/>}
    </article>
    <article className="timeline-card"><h2>Booking timeline</h2>{history?.map((item:any)=><div className="timeline-item" key={item.id}><strong>{String(item.to_status).replaceAll("_"," ")}</strong><small>{new Date(item.created_at).toLocaleString("en-NG")}</small>{item.reason&&<p>{item.reason}</p>}</div>)}</article></div>
    {renderedUpdates.length>0&&<section className="message-panel"><div className="section-heading"><p className="eyebrow">Expires after 24 hours</p><h2>Private work-in-progress updates</h2></div><div className="status-grid">{renderedUpdates.map(update=><article className="status-card" key={update.id}>{update.isVideo?<video src={update.signedUrl} controls preload="metadata"/>:<img src={update.signedUrl} alt="Private commission work in progress"/>}<p>{update.caption}</p><small>Expires {new Date(update.expires_at).toLocaleString("en-NG")}</small></article>)}</div></section>}
    <section className="message-panel"><div className="section-heading"><p className="eyebrow">Recorded communication</p><h2>Booking messages and private files</h2></div><div className="messages">{renderedMessages.map((message:any)=><article className={message.sender_id===user.id?"message mine":"message"} key={message.id}><p>{message.body}</p>{message.attachments.length>0&&<div className="message-attachments">{message.attachments.map((url:string,index:number)=><a href={url} target="_blank" rel="noopener noreferrer" key={url}>Open private attachment {index+1}</a>)}</div>}<small>{new Date(message.created_at).toLocaleString("en-NG")}</small></article>)}</div><form className="message-form" action={sendBookingMessage}><input type="hidden" name="booking_id" value={id}/><textarea name="body" required maxLength={5000} placeholder="Write a booking message…"/><div className="field"><label>Private attachments (optional)</label><input name="attachments" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" multiple/><small>Up to 3 JPG, PNG, WebP or PDF files, 15 MB each. Links expire after 15 minutes.</small></div><button className="button">Send message</button></form></section>
    {isCustomer&&status==="completed"&&!review&&<form className="application-form review-form" action={submitReview}><input type="hidden" name="booking_id" value={id}/><p className="eyebrow">Verified booking review</p><h2>Rate this commission</h2><div className="field-grid">{["overall","communication","quality","timeliness"].map(name=><div className="field" key={name}><label>{name}</label><select name={name} required defaultValue="5">{[5,4,3,2,1].map(value=><option value={value} key={value}>{value} / 5</option>)}</select></div>)}</div><div className="field"><label>Review</label><textarea name="body" required minLength={20} maxLength={2000}/></div><button className="button">Submit verified review</button></form>}
    {review&&<div className="status-message">Review submitted · {review.moderation_status}</div>}
    {isArtist&&review&&!review.artist_response&&<form className="application-form review-form" action={respondToReview}><input type="hidden" name="booking_id" value={id}/><h2>Respond to the verified review</h2><div className="field"><label>Public response</label><textarea name="artist_response" minLength={10} maxLength={1200} required/></div><button className="button">Publish response</button></form>}
  </section>;
}
function StateButton({id,to,label}:{id:string;to:string;label:string}){return <form action={transitionBooking}><input type="hidden" name="booking_id" value={id}/><input type="hidden" name="to_status" value={to}/><button className="button">{label}</button></form>}
function ReasonButton({id,to,label}:{id:string;to:string;label:string}){return <form className="reason-action" action={transitionBooking}><input type="hidden" name="booking_id" value={id}/><input type="hidden" name="to_status" value={to}/><textarea name="reason" minLength={10} required placeholder="Explain the issue or requested change…"/><button className="button reject">{label}</button></form>}
