"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createSupabaseAdminClient,createSupabaseServerClient } from "@/lib/supabase/server";
import { normalizeExternalUrl,normalizeInstagram,normalizeWhatsapp } from "@/lib/marketplace";

async function ownedArtist(){const client=await createSupabaseServerClient();const {data:{user}}=await client.auth.getUser();if(!user)redirect("/auth/login");const {data:artist}=await client.from("artists").select("id,slug,status").eq("owner_user_id",user.id).maybeSingle();if(!artist)throw new Error("No artist profile belongs to this account.");return {user,artist};}
export async function updateArtistProfile(formData:FormData){const {artist}=await ownedArtist();const admin=createSupabaseAdminClient();const update={business_name:String(formData.get("business_name")||"").trim(),owner_name:String(formData.get("owner_name")||"").trim(),bio:String(formData.get("bio")||"").trim(),whatsapp:normalizeWhatsapp(formData.get("whatsapp")),instagram:normalizeInstagram(formData.get("instagram")),portfolio_link:normalizeExternalUrl(formData.get("portfolio_link")),price_range:String(formData.get("price_range")||"").trim()||null,updated_at:new Date().toISOString()};if(update.business_name.length<2||update.owner_name.length<2||update.bio.length<80||update.bio.length>3000)throw new Error("Complete the artist name and write a bio between 80 and 3,000 characters.");const file=formData.get("profile_image");let uploadedPath:string|null=null;if(file instanceof File&&file.size){if(file.size>5*1024*1024||!["image/jpeg","image/png","image/webp"].includes(file.type))throw new Error("Use a JPG, PNG or WebP under 5 MB.");const extension=file.type.split("/")[1]||"jpg";uploadedPath=`${artist.slug}/profile-${crypto.randomUUID()}.${extension}`;const {error}=await admin.storage.from("artist-portfolios").upload(uploadedPath,file,{contentType:file.type});if(error)throw error;(update as any).profile_image_url=admin.storage.from("artist-portfolios").getPublicUrl(uploadedPath).data.publicUrl;}const {error}=await admin.from("artists").update(update).eq("id",artist.id);if(error){if(uploadedPath)await admin.storage.from("artist-portfolios").remove([uploadedPath]);throw error;}revalidatePath(`/artist/${artist.slug}`);revalidatePath("/dashboard/profile");}
export async function resubmitArtistApplication(){const {user,artist}=await ownedArtist();const admin=createSupabaseAdminClient();const {data:changed,error}=await admin.from("artists").update({status:"pending",moderation_reason:null,bookable:false,updated_at:new Date().toISOString()}).eq("id",artist.id).eq("status","rejected").select("id").maybeSingle();if(error)throw error;if(!changed)throw new Error("Only a rejected application can be resubmitted.");await admin.from("audit_logs").insert({actor_id:user.id,action:"artist.application.resubmitted",entity_type:"artist",entity_id:artist.id});revalidatePath("/dashboard");}
export async function publishArtistUpdate(formData:FormData){const {artist}=await ownedArtist();if(artist.status!=="approved")throw new Error("Only approved artist profiles can publish progress updates.");const caption=String(formData.get("caption")||"").trim();const visibility=String(formData.get("visibility")||"public");const consent=formData.get("client_consent")==="on";const bookingId=String(formData.get("booking_id")||"")||null;const file=formData.get("media");if(caption.length<3||caption.length>500)throw new Error("Write a caption between 3 and 500 characters.");if(!["public","booking_private"].includes(visibility))throw new Error("Choose a valid visibility setting.");if(visibility==="booking_private"&&!bookingId)throw new Error("Choose the booking that should receive this private update.");if(!(file instanceof File)||!file.size)throw new Error("Choose an image or short video.");if(file.size>25*1024*1024||!["image/jpeg","image/png","image/webp","video/mp4","video/webm"].includes(file.type))throw new Error("Use a supported image or video under 25 MB.");if(visibility==="public"&&!consent)throw new Error("Confirm you have permission to share this work publicly.");const admin=createSupabaseAdminClient();if(bookingId){const {data:booking}=await admin.from("bookings").select("id").eq("id",bookingId).eq("artist_id",artist.id).in("status",["funded","in_progress","awaiting_client_approval","revision_requested"]).maybeSingle();if(!booking)throw new Error("Choose one of your active bookings.");}const extension=file.type.split("/")[1]||"bin";const path=`${artist.id}/${crypto.randomUUID()}.${extension}`;const {error:uploadError}=await admin.storage.from("artist-updates").upload(path,file,{contentType:file.type});if(uploadError)throw uploadError;const {error}=await admin.from("artist_updates").insert({artist_id:artist.id,booking_id:bookingId,caption,media_url:path,visibility,client_consent:consent,moderation_status:visibility==="booking_private"?"published":"pending"});if(error){await admin.storage.from("artist-updates").remove([path]);throw error;}revalidatePath("/dashboard/status");}
