import { NextResponse } from "next/server";
import { createSupabaseAdminClient, createSupabaseServerClient, hasSupabase } from "@/lib/supabase/server";
import { categories as allowedCategories,states as allowedStates } from "@/lib/constants";
import { normalizeExternalUrl,normalizeInstagram,normalizeWhatsapp } from "@/lib/marketplace";
import { notifyAdmin } from "@/lib/notifications";

const safeSlug=(value:string)=>value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9\s-]/g,"").trim().replace(/\s+/g,"-").replace(/-+/g,"-");
export async function POST(request:Request){
  if(!hasSupabase || !process.env.SUPABASE_SERVICE_ROLE_KEY) return NextResponse.json({error:"Applications are not connected yet. Add the Supabase environment variables to enable submissions."},{status:503});
  try{
    const session=await createSupabaseServerClient(); const {data:{user}}=await session.auth.getUser();
    if(!user) return NextResponse.json({error:"Create and confirm your account before applying."},{status:401});
    const form=await request.formData(); const businessName=String(form.get("business_name")||"").trim(); const ownerName=String(form.get("owner_name")||"").trim(); const email=String(form.get("email")||"").trim(); const rawWhatsapp=String(form.get("whatsapp")||"").trim(); const bio=String(form.get("bio")||"").trim(); const categories=form.getAll("categories").map(String); const states=form.getAll("states_served").map(String); const images=form.getAll("images").filter((item):item is File=>item instanceof File && item.size>0);
    if(!businessName||!ownerName||!email||!rawWhatsapp||bio.length<80||!categories.length||!states.length||!images.length) return NextResponse.json({error:"Please complete every required field and choose at least one category and state."},{status:400});
    if(businessName.length>120||ownerName.length>120||bio.length>3000||!/^\S+@\S+\.\S+$/.test(email))return NextResponse.json({error:"Check the name, email address and bio length."},{status:400});
    let whatsapp:string,instagram:string|null,portfolioLink:string|null;try{whatsapp=normalizeWhatsapp(rawWhatsapp);instagram=normalizeInstagram(form.get("instagram"));portfolioLink=normalizeExternalUrl(form.get("portfolio_link"));}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Check the contact details."},{status:400});}
    if(states.length>3) return NextResponse.json({error:"Standard listings can serve up to 3 states. Want nationwide coverage? Ask about a Featured listing."},{status:400});
    const stateNames=new Set(allowedStates.map(item=>item.name));if(categories.some(category=>!allowedCategories.includes(category))||states.some(state=>!stateNames.has(state)))return NextResponse.json({error:"Choose only supported services and Nigerian locations."},{status:400});
    if(new Set(categories).size!==categories.length||new Set(states).size!==states.length)return NextResponse.json({error:"Remove duplicate services or locations."},{status:400});
    if(images.length>8||images.some((file)=>file.size>5*1024*1024)||images.some((file)=>!["image/jpeg","image/png","image/webp"].includes(file.type))) return NextResponse.json({error:"Upload up to 8 JPG, PNG or WebP images, no larger than 5 MB each."},{status:400});
    const supabase=createSupabaseAdminClient();const {data:owned}=await supabase.from("artists").select("id").eq("owner_user_id",user.id).maybeSingle();if(owned)return NextResponse.json({error:"This account already owns an artist profile."},{status:409}); let slug=safeSlug(businessName); const {data:existing}=await supabase.from("artists").select("slug").eq("slug",slug).maybeSingle(); if(existing) slug=`${slug}-${Date.now().toString().slice(-5)}`;
    let artistId="";const urls:string[]=[],paths:string[]=[];try{for(const [index,file] of images.entries()){const extension=file.type.split("/")[1]||"jpg"; const path=`${slug}/${crypto.randomUUID()}-${index}.${extension}`; const {error}=await supabase.storage.from("artist-portfolios").upload(path,file,{contentType:file.type,upsert:false}); if(error) throw error;paths.push(path); urls.push(supabase.storage.from("artist-portfolios").getPublicUrl(path).data.publicUrl);}const {data:artist,error}=await supabase.from("artists").insert({slug,business_name:businessName,owner_name:ownerName,email,whatsapp,bio,categories,states_served:states,profile_image_url:urls[0],portfolio_image_urls:urls,instagram,portfolio_link:portfolioLink,price_range:String(form.get("price_range")||"")||null,status:"pending",featured:false,featured_until:null,featured_tier:null,owner_user_id:user.id,verification_state:"claimed",bookable:false,base_state:states[0]}).select("id").single(); if(error) throw error;artistId=artist.id;}catch(error){if(paths.length)await supabase.storage.from("artist-portfolios").remove(paths);throw error;}
    await supabase.from("profiles").update({role:"artist",updated_at:new Date().toISOString()}).eq("user_id",user.id);
    await notifyAdmin({subject:`Artist application: ${businessName}`,text:`${ownerName} submitted ${businessName} for ${categories.join(", ")} in ${states.join(", ")}. Review it in the private admin dashboard.`,idempotencyKey:`artist-application/${artistId}`});
    return NextResponse.json({ok:true},{status:201});
  }catch(error){console.error(error);return NextResponse.json({error:"We couldn’t save the application. Please try again."},{status:500});}
}
